### ISSUE TITLE
error when running fti.py

### ISSUE THREAD

**Issue by deloittem** [MISP/vintage-misp-workbench#4]
Hello,

I was never able to run fti.py since I always receive the following error:

Traceback (most recent call last):
  File "fti.py", line 46, in <module>
    index_all(connector, schema)
  File "fti.py", line 11, in index_all
    ix = create_in("indexdir", schema)
  File "/usr/local/lib/python2.7/dist-packages/whoosh/index.py", line 102, in create_in
    return FileIndex.create(storage, schema, indexname)
  File "/usr/local/lib/python2.7/dist-packages/whoosh/index.py", line 425, in create
    TOC.create(storage, schema, indexname)
  File "/usr/local/lib/python2.7/dist-packages/whoosh/index.py", line 605, in create
    for filename in storage:
  File "/usr/local/lib/python2.7/dist-packages/whoosh/filedb/filestore.py", line 81, in **iter**
    return iter(self.list())
  File "/usr/local/lib/python2.7/dist-packages/whoosh/filedb/filestore.py", line 525, in list
    files = os.listdir(self.folder)
OSError: [Errno 2] No such file or directory: 'indexdir'

Any idea ?

Regards,
Mathieu

**Comment by adulau** [comment]
It seems that you are missing the indexdir directory:

OSError: [Errno 2] No such file or directory: 'indexdir'

A simple mkdir at the right place would do the job. (PR accepted too ;-)

Cheers

**Comment by Rafiot** [comment]
Thanks for the report :)

**Comment by deloittem** [comment]
Thank you for the answer ... error was obvious 
btw when I use grouping/website.py ... no events are displayed, empty list and I do not know the reason ... any idea about that ?
- config file is OK
- make_hashstore & make_snapshot do not report any error

**Comment by Rafiot** [comment]
If you connect to the redis-server with redis-cli, and run the command `info`, what does it says? to you have anything in the databases?
